const fontType = {
    'CS-Black' : 'CircularStd-Black',
    'CS-BlackItalic' : 'CircularStd-BlackItalic',
    'CS-Bold' : 'CircularStd-Bold',
    'CS-BoldItalic' : 'CircularStd-BoldItalic',
    'CS-Book' : 'CircularStd-Book',
    'CS-BookItalic' : 'CircularStd-BookItalic',
    'CS-LightItalic' : 'CircularStd-Light Italic',
    'CS-Light' : 'CircularStd-Light',
    'CS-Medium' : 'CircularStd-Medium',
    'CS-MediumItalic' : 'CircularStd-MediumItalic',
    'SP-Light' : 'sofiapro-light',
    'Pjs-ExtraLight' : 'PlusJakartaSans-ExtraLight',
    'Pjs-Light' : 'PlusJakartaSans-Light',
    'Pjs-Regular' : 'PlusJakartaSans-Regular',
    'Pjs-Medium' : 'PlusJakartaSans-Medium',
    'Pjs-SemiBold' : 'PlusJakartaSans-SemiBold',
    'Pjs-Bold' : 'PlusJakartaSans-Bold',
    'Pjs-ExtraBold' : 'PlusJakartaSans-ExtraBold',
}
export default fontType;